import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { CATALOGUE } from "../catalogue";
import type { ShapeDocument } from "../document";
import { kotlinExpression } from "./kotlin";

const ENGINE = resolve(process.cwd(), "../engine");
const GENERATED = resolve(ENGINE, "src/jvmTest/kotlin/io/github/kartollikaa/shapestudio/engine/export/ExportCases.kt");
const NOT_EXPORTED = new Set(["fillSquare", "startAngle"]);

function edited(name: string, change: (doc: ShapeDocument) => void): ShapeDocument {
  const doc = structuredClone(CATALOGUE[name]);
  change(doc);
  return doc;
}

function cases(): [string, ShapeDocument][] {
  const fixtures = readdirSync(resolve(ENGINE, "fixtures/documents"))
    .filter((f) => f.endsWith(".json"))
    .sort()
    .map((f): [string, ShapeDocument] => [`fixture/${f.replace(/\.json$/, "")}`, JSON.parse(readFileSync(resolve(ENGINE, "fixtures/documents", f), "utf8"))])
    .filter(([, doc]) => !(doc.transforms ?? []).some((t) => NOT_EXPORTED.has(t.type)));
  const changes: [string, string, (doc: ShapeDocument) => void][] = [
    ["cookie-rotated", "Cookie4Sided", (d) => { d.transforms!.unshift({ type: "rotate", degrees: 30 }); if (d.shape.kind === "polygon") d.shape.repeat!.count = 6; }],
    ["star", "Sunny", (d) => { if (d.shape.kind === "star") Object.assign(d.shape, { verticesPerRadius: 11, innerRadius: 0.6, rounding: { radius: 0.2, smoothing: 0.5 } }); }],
    ["ngon", "Triangle", (d) => { if (d.shape.kind === "ngon") Object.assign(d.shape, { vertices: 5, rounding: { radius: 0.3, smoothing: 0.4 } }); }],
    ["rectangle", "SemiCircle", (d) => { if (d.shape.kind === "rectangle") { d.shape.width = 2.2; d.shape.perVertexRounding = d.shape.perVertexRounding!.map((r) => ({ radius: r.radius / 2, smoothing: 0.6 })); } }],
    ["oval", "Oval", (d) => { d.transforms = [{ type: "scale", x: 1, y: 0.4 }, { type: "rotate", degrees: 20 }, { type: "normalize" }]; }],
    ["heart-dots", "Heart", (d) => { if (d.shape.kind === "polygon") { d.shape.vertices[1] = [0.85, -0.1]; d.shape.perVertexRounding![1] = { radius: 0.7, smoothing: 0.3 }; } }],
    ["pixel-rounded", "PixelCircle", (d) => { if (d.shape.kind === "polygon") d.shape.perVertexRounding = d.shape.perVertexRounding!.map(() => ({ radius: 0.05 })); }],
  ];
  return [
    ...Object.entries(CATALOGUE).map(([name, doc]): [string, ShapeDocument] => [`catalogue/${name}`, doc]),
    ...fixtures,
    ...changes.map(([name, base, change]): [string, ShapeDocument] => [`edited/${name}`, edited(base, change)]),
  ];
}

function source(): string {
  const imports = new Set<string>(["androidx.graphics.shapes.RoundedPolygon"]);
  const entries = cases().map(([name, doc]) => {
    const { code, imports: used } = kotlinExpression(doc);
    used.forEach((i) => imports.add(i));
    return `    ExportCase(\n        name = "${name}",\n        document = """${JSON.stringify(doc)}""",\n        exported = ${code.replace(/\n/g, "\n        ")},\n    ),`;
  });
  return `// Generated by web/src/export/round-trip.test.ts. Regenerate with: npm run round-trip -w web
package io.github.kartollikaa.shapestudio.engine.export

${[...imports].sort().map((i) => `import ${i}`).join("\n")}

internal val exportCases: List<ExportCase> = listOf(
${entries.join("\n")}
)
`;
}

describe("the Compose round trip", () => {
  it("has a committed JVM source that matches the exporter", () => {
    const expected = source();
    if (process.env.UPDATE_ROUND_TRIP === "1") writeFileSync(GENERATED, expected);
    const committed = readFileSync(GENERATED, "utf8");
    expect(committed === expected, "ExportCases.kt is stale; run npm run round-trip -w web").toBe(true);
  });
});
